[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
meme_chain_solana = "FgKLBQuE6Ksctz4gjFk1BjiBCcUqmnYFy7986ecuNqLS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/my-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
create-token = "npx ts-node scripts/create-test-token.ts"
buy-tokens = "npx ts-node scripts/buy-tokens.ts"
inspect-token = "npx ts-node scripts/inspect-token.ts"
sell-tokens = "npx ts-node scripts/sell-tokens.ts"
check-protocol = "npx ts-node scripts/check-protocol.ts"
list-tokens = "npx ts-node scripts/list-my-tokens.ts"